# Question 1

In [1]:
#numpy version
import numpy;
print(numpy.version.version)

1.24.3


In [3]:
#pandas version
import pandas as pd;
print(pd.__version__)

1.5.3


# Question 2

In [4]:
greetings = ('Hello HCIA PDTP-Huawei Team')
print(greetings)

Hello HCIA PDTP-Huawei Team


# Question 3

In [9]:
x = int(input('Enter a number: '))
y = int(input('Enter a number: '))

z = x + y
print('Sum = ',z)

Enter a number: 5
Enter a number: 5
Sum =  10


# Question 4

In [15]:
name = ('Cloud-track',)
#print(type(name))
print(name)

('Cloud-track',)


In [18]:
team = ('Grace', 'Ian', 'Daniel',)
for x in team:
    print(x)

Grace
Ian
Daniel


# Question 5

In [25]:
details = {
    'name' : 'Reagan',
    'phone' : '+254 722 222333',
}
print(details)

{'name': 'Reagan', 'phone': '+254 722 222333'}


# Question 6


In [33]:
# Qn 6a
def multiplication():
    num_1 = float(input('Enter a number: '))
    num_2 = float(input('Enter a number: '))
    
    product = num_1 * num_2
    print(f"Product of {num_1} x {num_2} = {product}")
    
multiplication()

Enter a number: 8
Enter a number: 6
Product of 8.0 x 6.0 = 48.0


In [34]:
#Qn 6b
def sqrProd(x,y):
    product = x * y
    square_product = product ** 2
    return square_product


# Question 7

In [36]:
#Qn 7
import numpy as np
arr = np.zeros((5,5))
print(arr)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
x = np.arange (0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [39]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

In [60]:
x = np.random.randint(low=1, high=100, size=(10,10))
print(x)

xmin, xmax = x.min(), x.max()
print(f'Minimum and Maximum values: {xmin} , {xmax}')

[[44 34 38 99 39 42 98 63 46  1]
 [15 68 82 49 96  8 60 37 12 17]
 [47 78 53 14 99 64  3 42  8 86]
 [20 61 22 52 91 13 87 47 97 57]
 [86 48  7  3 51 37 43 62 46 69]
 [51 27 95 35  9 48 32  2 70 48]
 [57 67 38 91  7 59 40 79 41 13]
 [54 99 66 42 93 69 85 19 34 44]
 [41 40  5 39 93 23 84 85  1  9]
 [83 11 40 61 63 64 82 45 60 84]]
Minimum and Maximum values: 1 , 99


In [58]:
x = np.random.randint(30, size=(6, 5))
print(x)
mean = np.mean(x)
print('Mean: ',mean)

[[11 28 21  8 25]
 [25  7  1  6  5]
 [ 4  6 17 12 14]
 [ 0  3 14 13 15]
 [ 4 12 15 26 28]
 [19 24  7  1 20]]
Mean:  13.033333333333333


# Question 8

In [61]:
x = int(input('Enter a number: '))
y = int(input('Enter a number: '))

z = x * y
print('Product = ',z)

Enter a number: 6
Enter a number: 6
Product =  36


# Question 9

In [1]:
def doubleList(numberList):
    for number in numberList:
        print(2 * number)
doubleList([3, 1, 5])


6
2
10
